FROM node:14-buster AS build
WORKDIR /app
COPY public/booking-app/package*.json ./
RUN npm install
COPY public/booking-app/ ./
RUN npm run build

FROM nginx:1.25-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
