FROM eclipse-temurin:11-jdk AS build

WORKDIR /workspace

COPY api/ ./

RUN chmod +x gradlew

RUN ./gradlew clean bootJar -x test --no-daemon

FROM eclipse-temurin:11-jre

WORKDIR /app

COPY --from=build /workspace/build/libs/*.jar app.jar

EXPOSE 7070

ENTRYPOINT ["java", "-jar", "app.jar"]
